param(
    [string]$SdkRoot = 'D:\ASWJ',
    [string]$Platform = 'android-35',
    [string]$BuildToolsVersion = '35.0.1',
    [switch]$BuildApk
)

$ErrorActionPreference = 'Stop'
$project = $PSScriptRoot
$androidJar = Join-Path $SdkRoot "platforms\$Platform\android.jar"
$buildTools = Join-Path $SdkRoot "build-tools\$BuildToolsVersion"
$d8 = Join-Path $buildTools 'd8.bat'
$aapt = Join-Path $buildTools 'aapt.exe'
$zipalign = Join-Path $buildTools 'zipalign.exe'
$apksigner = Join-Path $buildTools 'apksigner.bat'
$build = Join-Path $project 'input-helper\build'
$classesDir = Join-Path $build 'helper-classes'
$dexDir = Join-Path $build 'helper-dex'
$sources = @(Get-ChildItem (Join-Path $project 'input-helper\src') -Recurse -Filter '*.java' | ForEach-Object FullName)
$destination = Join-Path $build 'imgui_input.dex'
$apk = Join-Path $build 'dum_input.apk'
$embeddedDir = Join-Path $build 'embedded'
$manifest = Join-Path $project 'input-helper\AndroidManifest.xml'
$unsigned = Join-Path $build 'input-unsigned.apk'
$aligned = Join-Path $build 'input-aligned.apk'
$key = Join-Path $build 'debug.keystore'

foreach ($requiredFile in @($androidJar, $d8, $aapt, $zipalign, $apksigner)) {
    if (-not (Test-Path -LiteralPath $requiredFile -PathType Leaf)) { throw "Android SDK file not found: $requiredFile" }
}
foreach ($requiredCommand in @('java', 'javac', 'keytool')) {
    if (-not (Get-Command $requiredCommand -ErrorAction SilentlyContinue)) { throw "JDK command not found in PATH: $requiredCommand" }
}

if (Test-Path -LiteralPath $classesDir) {
    $resolvedClasses = (Resolve-Path -LiteralPath $classesDir).Path
    $buildPrefix = [System.IO.Path]::GetFullPath($build) + [System.IO.Path]::DirectorySeparatorChar
    if (-not $resolvedClasses.StartsWith($buildPrefix, [System.StringComparison]::OrdinalIgnoreCase)) {
        throw 'Class output must stay inside input-helper/build'
    }
    Remove-Item -LiteralPath $resolvedClasses -Recurse -Force
}
New-Item -ItemType Directory -Force $classesDir, $dexDir | Out-Null
& javac -source 8 -target 8 -cp $androidJar -d $classesDir $sources
if ($LASTEXITCODE -ne 0) { throw 'javac failed' }
$classFiles = @(Get-ChildItem $classesDir -Recurse -Filter '*.class' | ForEach-Object FullName)
& $d8 --lib $androidJar --output $dexDir $classFiles
if ($LASTEXITCODE -ne 0) { throw 'd8 failed' }
Copy-Item (Join-Path $dexDir 'classes.dex') $destination
if (-not $BuildApk) {
    Write-Host "Built $destination (no APK is built or installed)"
    return
}
& $aapt package -f -M $manifest -I $androidJar -F $unsigned
if ($LASTEXITCODE -ne 0) { throw 'aapt package failed' }
Push-Location $dexDir
try {
    & $aapt add $unsigned 'classes.dex'
    if ($LASTEXITCODE -ne 0) { throw 'aapt add failed' }
} finally { Pop-Location }
& $zipalign -f 4 $unsigned $aligned
if ($LASTEXITCODE -ne 0) { throw 'zipalign failed' }
if (-not (Test-Path $key)) {
    & keytool -genkeypair -keystore $key -storepass android -keypass android -alias androiddebugkey -dname 'CN=Android Debug,O=Android,C=US' -keyalg RSA -keysize 2048 -validity 10000 -noprompt
    if ($LASTEXITCODE -ne 0) { throw 'keytool failed' }
}
& $apksigner sign --v4-signing-enabled false --ks $key --ks-key-alias androiddebugkey --ks-pass pass:android --key-pass pass:android --out $apk $aligned
if ($LASTEXITCODE -ne 0) { throw 'apksigner failed' }

# Generated build input, not a second distributable: the APK already contains classes.dex.
New-Item -ItemType Directory -Force $embeddedDir | Out-Null
$payloadBytes = [System.IO.File]::ReadAllBytes($apk)
$header = [System.Text.StringBuilder]::new()
[void]$header.AppendLine('// Generated by build-input-helper.ps1; do not edit.')
[void]$header.AppendLine('#pragma once')
[void]$header.AppendLine('namespace DumPayload {')
[void]$header.AppendLine('alignas(16) inline constexpr unsigned char apk[] = {')
for ($offset = 0; $offset -lt $payloadBytes.Length; $offset += 16) {
    $last = [Math]::Min($offset + 15, $payloadBytes.Length - 1)
    $hexBytes = for ($index = $offset; $index -le $last; $index++) { '0x{0:x2}' -f $payloadBytes[$index] }
    [void]$header.AppendLine('    ' + ($hexBytes -join ',') + ',')
}
[void]$header.AppendLine('};')
[void]$header.AppendLine('}')
[System.IO.File]::WriteAllText((Join-Path $embeddedDir 'DumInputApk.h'), $header.ToString(), [System.Text.UTF8Encoding]::new($false))
Write-Host "Built embedded APK ($($payloadBytes.Length) bytes); intermediate files stay in $build"
